REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\cell_locator\cell_locator.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\cell_locator\arm\gccmain.o" -c "C:\Program Files\MRE_SDK\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\cell_locator\include" -I "D:\MyGitHub\cell_locator\include\service" -I "D:\MyGitHub\cell_locator\include\component" -I "D:\MyGitHub\cell_locator\ResID" -I "D:\MyGitHub\cell_locator\src\app\widget" -I "D:\MyGitHub\cell_locator\src\app\launcher" -I "D:\MyGitHub\cell_locator\src\app\wallpaper" -I "D:\MyGitHub\cell_locator\src\app\screen_lock" -I "D:\MyGitHub\cell_locator\include\service" -I "D:\MyGitHub\cell_locator\include\component" -I "D:\MyGitHub\cell_locator\include\service" -I "D:\MyGitHub\cell_locator\src\framework" -I "D:\MyGitHub\cell_locator\src\framework\ui_core\base" -I "D:\MyGitHub\cell_locator\src\framework\ui_core\mvc" -I "D:\MyGitHub\cell_locator\src\framework\ui_core\pme" -I "D:\MyGitHub\cell_locator\src\framework\mmi_core" -I "D:\MyGitHub\cell_locator\src\ui_engine\vrt\interface" -I "D:\MyGitHub\cell_locator\src\component" -I "D:\MyGitHub\cell_locator\src\ui_engine\framework\xml" -I "D:\MyGitHub\cell_locator"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\cell_locator\arm\cell_locator.o" -c "d:\MyGitHub\cell_locator\cell_locator.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\cell_locator\include" -I "D:\MyGitHub\cell_locator\include\service" -I "D:\MyGitHub\cell_locator\include\component" -I "D:\MyGitHub\cell_locator\ResID" -I "D:\MyGitHub\cell_locator\src\app\widget" -I "D:\MyGitHub\cell_locator\src\app\launcher" -I "D:\MyGitHub\cell_locator\src\app\wallpaper" -I "D:\MyGitHub\cell_locator\src\app\screen_lock" -I "D:\MyGitHub\cell_locator\include\service" -I "D:\MyGitHub\cell_locator\include\component" -I "D:\MyGitHub\cell_locator\include\service" -I "D:\MyGitHub\cell_locator\src\framework" -I "D:\MyGitHub\cell_locator\src\framework\ui_core\base" -I "D:\MyGitHub\cell_locator\src\framework\ui_core\mvc" -I "D:\MyGitHub\cell_locator\src\framework\ui_core\pme" -I "D:\MyGitHub\cell_locator\src\framework\mmi_core" -I "D:\MyGitHub\cell_locator\src\ui_engine\vrt\interface" -I "D:\MyGitHub\cell_locator\src\component" -I "D:\MyGitHub\cell_locator\src\ui_engine\framework\xml" -I "D:\MyGitHub\cell_locator"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\cell_locator\cell_locator.axf"  "D:\MyGitHub\cell_locator\arm\gccmain.o"  "D:\MyGitHub\cell_locator\arm\cell_locator.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\scat.ld" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\percommon.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perfile.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persim.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persysstorage.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persysfile.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perlbs.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\peraudio.a"
REM Pack resource to app 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\cell_locator\cell_locator.pkd" -e AXF "D:\MyGitHub\cell_locator\cell_locator.vcproj" "D:\MyGitHub\cell_locator\cell_locator.axf"
REM Add tag infromation 
"C:\Program Files\MRE_SDK\tools\PackDigist.exe" "D:\MyGitHub\cell_locator\cell_locator.vcproj" "cell_locator" "0.1.0" "RDZDX" "1500" "NotSupportBg" "Not Support rotate" "cell_locator" "cell_locator" "cell_locator" "9123456789123456" "content" " File SIM card SysStorage SysFile LBS Audio" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\cell_locator\arm D:\MyGitHub\cell_locator\build.log

